# Generated by Django 4.2.5 on 2024-05-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepi_name', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recepies',
            name='image',
            field=models.ImageField(upload_to='Image/'),
        ),
    ]
